remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: [Meghan Myles]
description: [A repository for projects and other interesting stuff!]
link: [View my LinkedIn](https://www.linkedin.com/in/meghan-myles-28b15bb8/)
